name: Update site files

on:
  push:
    branches:
      - master  # 只在master上push触发部署
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  update:

    runs-on: ubuntu-18.04   # 使用ubuntu系统镜像运行自动化脚本

    steps:
    - name: Go to workdir
      run: |
        sudo su
        cd /home/jackyfeng/j_blogs
        source env/bin/activate
        cd j_django_blog
        
    - name: Update files
      run: |
        git pull orgin master
       
    - name: Restart server
      run: |
        python3 manage.py collectstatic
        python3 manage.py migrate
        sudo service nginx restart
        pkill gunicorn
        gunicorn --bind unix:/tmp/jackypy.xyz.socket j_django_blog.wsgi:application
        
    - name: Other things
      run: |
        cd ../time_plan_design
        gunicorn --bind unix:/tmp/timeplan.jackypy.xyz.socket time_plan_design.wsgi:application
